cd /home/studs/s466140/lab0
cp chandelure6 magmortar0/spheal                                                                                                                     # скопировать файл chandelure6 в директорию magmortar0/spheal
ln jolteon4 archeops4/sandshrew/exploud/shelmetjolteon                                                                                               # cоздать жесткую ссылку для файла jolteon4 с именем archeops4/sandshrew/exploud/shelmetjolteon
ln -s jolteon4 houndoom1/hippopotas/camerupt/remoraidjolteon                                                                                         # cоздать символическую ссылку для файла jolteon4 с именем houndoom1/hippopotas/camerupt/remoraidjolteon
cp -r archeops4 magmortar0/lileep/sneasel/cleffa                                                                                                     # скопировать рекурсивно директорию archeops4 в директорию magmortar0/lileep/sneasel/cleffa
cp chandelure6 houndoom1/crawdaunt/kirliachandelure                                                                                                  # скопировать содержимое файла chandelure6 в новый файл houndoom1/crawdaunt/kirliachandelure
cp chandelure6 houndoom1/crawdaunt/zoroark/infernape                                                                                                 # скопировать файл chandelure6 в директорию houndoom1/crawdaunt/zoroark/infernape
cp chandelure6 houndoom1/crawdaunt/zoroark/ampharoschandelure                                                                                        # скопировать содержимое файла chandelure6 в новый файл houndoom1/crawdaunt/zoroark/ampharoschandelure
ln -s archeops4 Copy_34                                                                                                                              # создать символическую ссылку c именем Copy_34 на директорию archeops4 в каталоге lab0
ln -s feraligatr6 houndoom1/crawdaunt/beedrillferaligatr                                                                                             # cоздать символическую ссылку для файла feraligatr6 с именем houndoom1/crawdaunt/beedrillferaligatr
cp -r magmortar0 houndoom1/crawdaunt/zoroark/samurott                                                                                                # скопировать рекурсивно директорию magmortar0 в директорию houndoom1/crawdaunt/zoroark/samurott
cat archeops4/charizard magmortar0/spheal/venipede/samurott houndoom1/crawdaunt/zoroark/ampharos magmortar0/spheal/horsea/darmanitan >feraligatr6_61 # объеденить содержимое файлов archeops4/charizard, magmortar0/spheal/venipede/samurott, houndoom1/crawdaunt/zoroark/ampharos, magmortar0/spheal/horsea/darmanitan, в новый файл feraligatr6_61
ln feraligatr6 houndoom1/crawdaunt/zoroark/purrloinferaligatr                                                                                        # cоздать жесткую ссылку для файла feraligatr6 с именем houndoom1/crawdaunt/zoroark/purrloinferaligatr
ln -s archeops4 Copy_89                                                                                                                              # создать символическую ссылку c именем Copy_89 на директорию archeops4 в каталоге lab0
ln feraligatr6 houndoom1/stunkyferaligatr                                                                                                            # cоздать жесткую ссылку для файла feraligatr6 с именем houndoom1/stunkyferaligatr
ln -s feraligatr6 archeops4/sandshrew/exploud/wailmerferaligatr                                                                                      # cоздать символическую ссылку для файла feraligatr6 с именем archeops4/sandshrew/exploud/wailmerferaligatr
cat archeops4/sandshrew/magmortar magmortar0/spheal/pineco houndoom1/crawdaunt/zoroark/purrloin magmortar0/spheal/lotad/cyndaquil >jolteon4_11       # объеденить содержимое файлов archeops4/sandshrew/magmortar, magmortar0/spheal/pineco, houndoom1/crawdaunt/zoroark/purrloin, magmortar0/spheal/lotad/cyndaquil, в новый файл jolteon4_11
cat magmortar0/spheal/lotad/gallade houndoom1/crawdaunt/kirlia houndoom1/crawdaunt/sudowoodo/crawdaunt houndoom1/stunky >jolteon4_30                 # объеденить содержимое файлов magmortar0/spheal/lotad/gallade, houndoom1/crawdaunt/kirlia, houndoom1/crawdaunt/sudowoodo/crawdaunt, houndoom1/stunky, в новый файл jolteon4_30
rm -rf houndoom1/stunkyferaligatr && cp feraligatr6 houndoom1/stunkyferaligatr                                                                       # скопировать содержимое файла feraligatr6 в новый файл houndoom1/stunkyferaligatr
cp feraligatr6 houndoom1/crawdaunt/whiscash/xatu                                                                                                     # скопировать файл feraligatr6 в директорию houndoom1/crawdaunt/whiscash/xatu
cp -r houndoom1 /tmp && cp -r /tmp/houndoom1 houndoom1/hippopotas/octillery/tirtouga                                                                                              # скопировать рекурсивно директорию houndoom1 в директорию houndoom1/hippopotas/octillery/tirtouga
ln -s magmortar0 Copy_53                                                                                                                             # создать символическую ссылку c именем Copy_53 на директорию magmortar0 в каталоге lab0
